services:
  mongodb:
    volumes:
      - mongodb_data:/data/db

  redis:
    volumes:
      - redis_data:/data
      - ./config/redis/redis.conf:/etc/redis/redis.conf:ro

  backend:
    container_name: backend
    hostname: backend
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/${MONGODB_DATABASE}
      - REDIS_URI=redis://redis:6379
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    container_name: frontend
    hostname: frontend
    restart: unless-stopped

  nginx:
    depends_on:
      - backend
      - frontend
    volumes:
      - ./config/nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/proxy_params:/etc/nginx/proxy_params:ro
      - ./logs/nginx:/var/log/nginx
    restart: unless-stopped

volumes:
  mongodb_data:
  redis_data:
